services:
    _defaults:
        autoconfigure: true
        autowire: true

    InspiredMinds\ContaoCategoriesNewsfilter\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoCategoriesNewsFilterBundle.php}
